source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!
target 'Reciplease' do
project '/Users/Bamzoule/Developer/Open Classrooms/Projets/P10_Richardier_Ianis/Reciplease/Reciplease.xcodeproj'
    pod 'Alamofire', '~> 4.4'
end
